### ISSUE TITLE
Cant find service characteristic

### ISSUE THREAD

**Issue by francismurtagh** [MatthiasKerat/BLETutorialYt#1]
Hi thanks for the tutorial.

I'm trying to connect to an arduino nano 33 ble.

The final app gets stuck when trying to find characteristic and says "Could not find temp and humidity publisher".
This is because it doesn't find UUID in this block:

```
 private fun findCharacteristics(serviceUUID: String, characteristicsUUID:String):BluetoothGattCharacteristic?{
        return gatt?.services?.find { service ->
            service.uuid.toString() == serviceUUID
        }?.characteristics?.find { characteristics ->
            characteristics.uuid.toString() == characteristicsUUID
        }
    }
```

The code for thermostat is taken from here:
https://github.com/bkolicoski/arduino-ble-thermostat/blob/main/BLEThermostat.ino

I'm able to connect with LightBlue App without issue to the nano.

Im not sure which are the correct UUIDs I should be using:
                   
```
-const val CCCD_DESCRIPTOR_UUID = "00002902-0000-1000-8000-00805F9B34FB"
+const val CCCD_DESCRIPTOR_UUID = "19B10000-E8F2-537E-4F6C-D104768A1214"
...
-    private val DEVICE_NAME = "Jinou_Sensor_HumiTemp"
-    private val TEMP_HUMIDITY_SERVICE_UIID = "0000aa20-0000-1000-8000-00805f9b34fb"
-    private val TEMP_HUMIDITY_CHARACTERISTICS_UUID = "0000aa21-0000-1000-8000-00805f9b34fb"
+    private val DEVICE_NAME = "Thermostat"
+    private val TEMP_HUMIDITY_SERVICE_UIID = "19b10000-e8f2-537e-4f6c-d104768a1214"
+    private val TEMP_HUMIDITY_CHARACTERISTICS_UUID = "19B10001-E8F2-537E-4F6C-D104768A1214"
```

Thanks again,
Francis.

**Comment by francismurtagh** [comment]
Debugging gives what looks like promising outputs:

> D/BluetoothGatt: Service 00001800-0000-1000-8000-00805f9b34fb
    Characteristics:
    |--00002a00-0000-1000-8000-00805f9b34fb: READABLE
    |--00002a01-0000-1000-8000-00805f9b34fb: READABLE
D/BluetoothGatt: Service 00001801-0000-1000-8000-00805f9b34fb
    Characteristics:
    |--00002a05-0000-1000-8000-00805f9b34fb: INDICATABLE
    |------00002902-0000-1000-8000-00805f9b34fb: EMPTY
D/BluetoothGatt: Service 19b10000-e8f2-537e-4f6c-d104768a1214
    Characteristics:
    |--19b10001-e8f2-537e-4f6c-d104768a1214: READABLE, WRITABLE, NOTIFIABLE
    |------00002902-0000-1000-8000-00805f9b34fb: EMPTY
    |--19b10002-e8f2-537e-4f6c-d104768a1214: READABLE, NOTIFIABLE
    |------00002902-0000-1000-8000-00805f9b34fb: EMPTY
    |--19b10003-e8f2-537e-4f6c-d104768a1214: READABLE, NOTIFIABLE
    |------00002902-0000-1000-8000-00805f9b34fb: EMPTY
    |--00002a6e-0000-1000-8000-00805f9b34fb: READABLE, WRITABLE, NOTIFIABLE
    |------00002902-0000-1000-8000-00805f9b34fb: EMPTY
    |--00002a6f-0000-1000-8000-00805f9b34fb: READABLE, NOTIFIABLE
    |------00002902-0000-1000-8000-00805f9b34fb: EMPTY

**Comment by MatthiasKerat** [comment]
Difficult to say without seeing the whole code. Multiple things could cause this like not initializing the gatt for example. Did you debug everything from searching the device, requesting MTU and so on? Maybe also its case sensitive since your CHARACTERISTICS_UUID value is upper case (Not sure if this even makes a difference tho). Gatt table looks also fine

**Comment by francismurtagh** [comment]
gatt seems to be there and has correct service uuid and characteristic uuid, ooh I'll try lowercase, good spot thanks.


> gatt = {BluetoothGatt@23392} 
>  mAdapter = {BluetoothAdapter@23404} 
>  mAttributionSource = {AttributionSource@23405} "AttributionSource { uid = 10732, packageName = com.example.bletutorial, attributionTag = null, token = android.os.Binder@ce272a3, next = null }"
>  mAuthRetryState = 0
>  mAutoConnect = false
>  mBluetoothGattCallback = {BluetoothGatt$1@23406} 
>  mBluetoothStateChangeCallback = {BluetoothGatt$2@23407} 
>  mCallback = {TemperatureAndHumidityBLEReceiveManager$gattCallback$1@23393} com.example.bletutorial.data.ble.TemperatureAndHumidityBLEReceiveManager$gattCallback$1@2d581d2
>  mClientIf = 21
>  mConnState = 2
>  mDevice = {BluetoothDevice@23408} "3F:1F:81:AD:72:6A"
>  mDeviceBusy = {Boolean@23409} false
>  mDeviceBusyLock = {Object@23410} 
>  mHandler = null
>  mOpportunistic = false
>  mPhy = 1
>  mService = {IBluetoothGatt$Stub$Proxy@23411} 
>  mServices = {ArrayList@23412}  size = 3
>   0 = {BluetoothGattService@23419} 
>    mAdvertisePreferred = false
>    mCharacteristics = {ArrayList@23422}  size = 2
>    mDevice = {BluetoothDevice@23408} "3F:1F:81:AD:72:6A"
>    mHandles = 0
>    mIncludedServices = {ArrayList@23423}  size = 0
>    mInstanceId = 1
>    mServiceType = 0
>    mUuid = {UUID@23424} "00001800-0000-1000-8000-00805f9b34fb"
>    shadow$_klass_ = {Class@10472} "class android.bluetooth.BluetoothGattService"
>    shadow$_monitor_ = 0
>   1 = {BluetoothGattService@23420} 
>    mAdvertisePreferred = false
>    mCharacteristics = {ArrayList@23427}  size = 1
>    mDevice = {BluetoothDevice@23408} "3F:1F:81:AD:72:6A"
>    mHandles = 0
>    mIncludedServices = {ArrayList@23428}  size = 0
>    mInstanceId = 6
>    mServiceType = 0
>    mUuid = {UUID@23429} "00001801-0000-1000-8000-00805f9b34fb"
>    shadow$_klass_ = {Class@10472} "class android.bluetooth.BluetoothGattService"
>    shadow$_monitor_ = 0
>   2 = {BluetoothGattService@23421} 
>    mAdvertisePreferred = false
>    mCharacteristics = {ArrayList@23432}  size = 5
>     0 = {BluetoothGattCharacteristic@23445} 
>      mDescriptors = {ArrayList@23450}  size = 1
>      mInstance = 12
>      mKeySize = 16
>      mPermissions = 0
>      mProperties = 26
>      mService = {BluetoothGattService@23421} 
>      mUuid = {UUID@23451} "19b10001-e8f2-537e-4f6c-d104768a1214"
>      mValue = null
>      mWriteType = 2
>      shadow$_klass_ = {Class@23091} "class android.bluetooth.BluetoothGattCharacteristic"
>      shadow$_monitor_ = 0
>     1 = {BluetoothGattCharacteristic@23446} 
>     2 = {BluetoothGattCharacteristic@23447} 
>     3 = {BluetoothGattCharacteristic@23448} 
>     4 = {BluetoothGattCharacteristic@23449} 
>    mDevice = {BluetoothDevice@23408} "3F:1F:81:AD:72:6A"
>    mHandles = 0
>    mIncludedServices = {ArrayList@23433}  size = 0
>    mInstanceId = 10
>    mServiceType = 0
>    mUuid = {UUID@23434} "19b10000-e8f2-537e-4f6c-d104768a1214"

**Comment by francismurtagh** [comment]
OK it's now reading the characteristic thanks.

> characteristic = {BluetoothGattCharacteristic@23297} 
>  mDescriptors = {ArrayList@23301}  size = 1
>  mInstance = 12
>  mKeySize = 16
>  mPermissions = 0
>  mProperties = 26
>  mService = {BluetoothGattService@23302} 
>  mUuid = {UUID@23303} "19b10001-e8f2-537e-4f6c-d104768a1214"
>  mValue = null
>  mWriteType = 2
>  shadow$_klass_ = {Class@22994} "class android.bluetooth.BluetoothGattCharacteristic"
>  shadow$_monitor_ = 0

Now stuck on Adjusting MTU space, so I'll try to debug further.

**Comment by MatthiasKerat** [comment]
Was the case sensitivity the problem? you say it stucks on adjusting MTU space but you already read from characteristics. That means that you read that before? Be careful adjusting MTU needs to be done before interacting with the device

**Comment by francismurtagh** [comment]
Ah OK I debugged it to this point and I believe I might be going out of bounds here as my thermostat has only 1 temp value and no humidity value.


```
 UUID.fromString(TEMP_HUMIDITY_CHARACTERISTICS_UUID) -> {
 //XX XX XX XX XX XX
val multiplicator = if(value.first().toInt()> 0) -1 else 1
val temperature = value[1].toInt() + value[2].toInt() / 10f
val humidity = value[4].toInt() + value[5].toInt() / 10f
```

**Comment by MatthiasKerat** [comment]
Well yeah you need to check this in the specification of your device :)
